version: '3'
services:
  api:
    build: .
    working_dir: /repo
    volumes:
      - ness-api-function:/repo
    environment:
      PORT: ${PORT}
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
      FCM_CREDENTIALS_JSON_BASE64: ${FCM_CREDENTIALS_JSON_BASE64}
    ports:
      - 3000:3000
    tty: true
  db-with-gui:
    image: instructure/dynamo-local-admin
    ports:
      - 8000:8000
volumes:
  ness-api-function:
    external: true
  ness-api-data:
    external: true
networks:
  default:
    external:
      name: ness-network
