version: '3'
services:
  api:
    build: .
    working_dir: /repo
    volumes:
      - ness-api-function:/repo
    environment:
      PORT: ${PORT}
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
    ports:
      - 3000:3000
    tty: true
  db-with-gui:
    image: instructure/dynamo-local-admin
    ports:
      - 8000:8000
  aws-cli:
    image: amazon/aws-cli
    entrypoint: /bin/sh -c "while :; do sleep 10; done"
    tty: true
    environment:
      AWS_ACCESS_KEY_ID: dammy
      AWS_SECRET_ACCESS_KEY: dammy
volumes:
  ness-api-function:
    external: true
  ness-api-data:
    external: true
networks:
  default:
    external:
      name: ness-network
