version: '3'
services:
  api:
    build: .
    working_dir: /repo
    volumes:
      - ness-api-function:/repo
    environment:
      PORT: ${PORT}
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
      FCM_CREDENTIALS_JSON_BASE64: ${FCM_CREDENTIALS_JSON_BASE64}
      ELASTICSEARCH_ADDRESS_1: ${ELASTICSEARCH_ADDRESS_1}
      ELASTICSEARCH_ADDRESS_2: ${ELASTICSEARCH_ADDRESS_2}
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
    ports:
      - 3000:3000
    tty: true
  db-with-gui:
    image: instructure/dynamo-local-admin
    ports:
      - 8000:8000
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
volumes:
  ness-api-function:
    external: true
  ness-api-data:
    external: true
networks:
  default:
    external:
      name: ness-network
