version: '3'
services:
  app:
    build: .
    working_dir: /repo
    volumes:
      - ness-function:/repo
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
    tty: true
volumes:
  ness-function:
    external: true
