// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
}

type CloseThread struct {
	ThreadID string `json:"threadID"`
}

type GetThreadsInput struct {
	Limit             *int    `json:"limit"`
	LastEvaluatedTime *string `json:"lastEvaluatedTime"`
	Closed            *bool   `json:"closed"`
}

type NewThread struct {
	Title string `json:"title"`
}

type Thread struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Closed    bool   `json:"closed"`
	CreatedAt string `json:"createdAt"`
}

func (Thread) IsNode() {}
