// Package xogen contains the types for schema 'public'.
package xogen

// Code generated by xo. DO NOT EDIT.

// Digest calls the stored procedure 'public.digest(bytea, text, text, text) bytea' on db.
func Digest(db XODB, v0 []byte, v1 string, v2 string, v3 string) ([]byte, error) {
	var err error

	// sql query
	const sqlstr = `SELECT public.digest($1, $2, $3, $4)`

	// run query
	var ret []byte
	XOLog(sqlstr, v0, v1, v2, v3)
	err = db.QueryRow(sqlstr, v0, v1, v2, v3).Scan(&ret)
	if err != nil {
		return nil, err
	}

	return ret, nil
}
