// Package xogen contains the types for schema 'public'.
package xogen

// Code generated by xo. DO NOT EDIT.

// Dearmor calls the stored procedure 'public.dearmor(text) bytea' on db.
func Dearmor(db XODB, v0 string) ([]byte, error) {
	var err error

	// sql query
	const sqlstr = `SELECT public.dearmor($1)`

	// run query
	var ret []byte
	XOLog(sqlstr, v0)
	err = db.QueryRow(sqlstr, v0).Scan(&ret)
	if err != nil {
		return nil, err
	}

	return ret, nil
}
