// Package xogen contains the types for schema 'public'.
package xogen

// Code generated by xo. DO NOT EDIT.

// DecryptIv calls the stored procedure 'public.decrypt_iv(bytea, bytea, bytea, text) bytea' on db.
func DecryptIv(db XODB, v0 []byte, v1 []byte, v2 []byte, v3 string) ([]byte, error) {
	var err error

	// sql query
	const sqlstr = `SELECT public.decrypt_iv($1, $2, $3, $4)`

	// run query
	var ret []byte
	XOLog(sqlstr, v0, v1, v2, v3)
	err = db.QueryRow(sqlstr, v0, v1, v2, v3).Scan(&ret)
	if err != nil {
		return nil, err
	}

	return ret, nil
}
