// Package xogen contains the types for schema 'public'.
package xogen

import "github.com/google/uuid"

// Code generated by xo. DO NOT EDIT.

// GenRandomUUID calls the stored procedure 'public.gen_random_uuid() uuid' on db.
func GenRandomUUID(db XODB) (uuid.UUID, error) {
	var err error

	// sql query
	const sqlstr = `SELECT public.gen_random_uuid()`

	// run query
	var ret uuid.UUID
	XOLog(sqlstr)
	err = db.QueryRow(sqlstr).Scan(&ret)
	if err != nil {
		return uuid.New(), err
	}

	return ret, nil
}
