// Package xogen contains the types for schema 'public'.
package xogen

// Code generated by xo. DO NOT EDIT.

// Hmac calls the stored procedure 'public.hmac(bytea, bytea, text, text, text, text) bytea' on db.
func Hmac(db XODB, v0 []byte, v1 []byte, v2 string, v3 string, v4 string, v5 string) ([]byte, error) {
	var err error

	// sql query
	const sqlstr = `SELECT public.hmac($1, $2, $3, $4, $5, $6)`

	// run query
	var ret []byte
	XOLog(sqlstr, v0, v1, v2, v3, v4, v5)
	err = db.QueryRow(sqlstr, v0, v1, v2, v3, v4, v5).Scan(&ret)
	if err != nil {
		return nil, err
	}

	return ret, nil
}
