// Package xogen contains the types for schema 'public'.
package xogen

// Code generated by xo. DO NOT EDIT.

// PgpPubDecrypt calls the stored procedure 'public.pgp_pub_decrypt(bytea, bytea, bytea, bytea, text, bytea, bytea, text, text) text' on db.
func PgpPubDecrypt(db XODB, v0 []byte, v1 []byte, v2 []byte, v3 []byte, v4 string, v5 []byte, v6 []byte, v7 string, v8 string) (string, error) {
	var err error

	// sql query
	const sqlstr = `SELECT public.pgp_pub_decrypt($1, $2, $3, $4, $5, $6, $7, $8, $9)`

	// run query
	var ret string
	XOLog(sqlstr, v0, v1, v2, v3, v4, v5, v6, v7, v8)
	err = db.QueryRow(sqlstr, v0, v1, v2, v3, v4, v5, v6, v7, v8).Scan(&ret)
	if err != nil {
		return "", err
	}

	return ret, nil
}
