// Package xogen contains the types for schema 'public'.
package xogen

// Code generated by xo. DO NOT EDIT.

// PgpPubEncrypt calls the stored procedure 'public.pgp_pub_encrypt(text, bytea, text, bytea, text) bytea' on db.
func PgpPubEncrypt(db XODB, v0 string, v1 []byte, v2 string, v3 []byte, v4 string) ([]byte, error) {
	var err error

	// sql query
	const sqlstr = `SELECT public.pgp_pub_encrypt($1, $2, $3, $4, $5)`

	// run query
	var ret []byte
	XOLog(sqlstr, v0, v1, v2, v3, v4)
	err = db.QueryRow(sqlstr, v0, v1, v2, v3, v4).Scan(&ret)
	if err != nil {
		return nil, err
	}

	return ret, nil
}
