// Package xogen contains the types for schema 'public'.
package xogen

// Code generated by xo. DO NOT EDIT.

// PgpKeyID calls the stored procedure 'public.pgp_key_id(bytea) text' on db.
func PgpKeyID(db XODB, v0 []byte) (string, error) {
	var err error

	// sql query
	const sqlstr = `SELECT public.pgp_key_id($1)`

	// run query
	var ret string
	XOLog(sqlstr, v0)
	err = db.QueryRow(sqlstr, v0).Scan(&ret)
	if err != nil {
		return "", err
	}

	return ret, nil
}
