// Package xogen contains the types for schema 'public'.
package xogen

// Code generated by xo. DO NOT EDIT.

// PgpArmorHeaders calls the stored procedure 'public.pgp_armor_headers(text) SETOF record' on db.
func PgpArmorHeaders(db XODB, v0 string) ([]Record, error) {
	var err error

	// sql query
	const sqlstr = `SELECT public.pgp_armor_headers($1)`

	// run query
	var ret []Record
	XOLog(sqlstr, v0)
	err = db.QueryRow(sqlstr, v0).Scan(&ret)
	if err != nil {
		return nil, err
	}

	return ret, nil
}
