// Package xogen contains the types for schema 'public'.
package xogen

// Code generated by xo. DO NOT EDIT.

// PgpSymDecryptBytea calls the stored procedure 'public.pgp_sym_decrypt_bytea(bytea, text, bytea, text, text) bytea' on db.
func PgpSymDecryptBytea(db XODB, v0 []byte, v1 string, v2 []byte, v3 string, v4 string) ([]byte, error) {
	var err error

	// sql query
	const sqlstr = `SELECT public.pgp_sym_decrypt_bytea($1, $2, $3, $4, $5)`

	// run query
	var ret []byte
	XOLog(sqlstr, v0, v1, v2, v3, v4)
	err = db.QueryRow(sqlstr, v0, v1, v2, v3, v4).Scan(&ret)
	if err != nil {
		return nil, err
	}

	return ret, nil
}
